format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
${custom.caffeinate}\
$fill\
$all\
"""

command_timeout = 750

[aws]
disabled = true

[buf]
disabled = true

[custom.caffeinate]
style = 'bold #6c71c4'
symbol = 'ïƒ´  '
when = 'pgrep caffeinate'

[directory]
truncation_symbol = ".../"
truncate_to_repo = false

[docker_context]
disabled = true

[fill]
symbol = " "

[gcloud]
disabled = true

[git_branch]
truncation_length = 36

[kubernetes]
disabled = false

[status]
disabled = false
format = '[$symbol $common_meaning $signal_name $int\]($style)'
map_symbol = true
pipestatus = true
recognize_signal_code = true
success_symbol = ''
